import { FirewallRule } from './firewall-engine';
import { v4 as uuidv4 } from 'uuid';

export const defaultRules: FirewallRule[] = [
  {
    id: uuidv4(),
    priority: 10,
    enabled: true,
    zone: 'WAN_TO_DMZ',
    srcIp: 'any',
    destIp: '192.168.100.10',
    srcPort: 'any',
    destPort: '80',
    protocol: 'TCP',
    action: 'ALLOW',
    description: 'Allow HTTP traffic from WAN to DMZ Web Server',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 20,
    enabled: true,
    zone: 'WAN_TO_DMZ',
    srcIp: 'any',
    destIp: '192.168.100.10',
    srcPort: 'any',
    destPort: '443',
    protocol: 'TCP',
    action: 'ALLOW',
    description: 'Allow HTTPS traffic from WAN to DMZ Web Server',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 30,
    enabled: true,
    zone: 'WAN_TO_DMZ',
    srcIp: 'any',
    destIp: '192.168.100.20',
    srcPort: 'any',
    destPort: '25',
    protocol: 'TCP',
    action: 'ALLOW',
    description: 'Allow SMTP traffic from WAN to DMZ Mail Server',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 40,
    enabled: true,
    zone: 'WAN_TO_DMZ',
    srcIp: 'any',
    destIp: 'any',
    srcPort: 'any',
    destPort: '22',
    protocol: 'TCP',
    action: 'DENY',
    description: 'Block SSH access to DMZ from WAN (brute-force protection)',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 50,
    enabled: true,
    zone: 'DMZ_TO_LAN',
    srcIp: '192.168.100.10',
    destIp: '10.0.0.5',
    srcPort: 'any',
    destPort: '3306',
    protocol: 'TCP',
    action: 'ALLOW',
    description: 'Allow DMZ Web Server to query internal Database Server (MySQL)',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 60,
    enabled: true,
    zone: 'DMZ_TO_LAN',
    srcIp: 'any',
    destIp: 'any',
    srcPort: 'any',
    destPort: 'any',
    protocol: 'ANY',
    action: 'DENY',
    description: 'Block all unauthorized DMZ to LAN lateral movement',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 70,
    enabled: true,
    zone: 'WAN_TO_LAN',
    srcIp: 'any',
    destIp: 'any',
    srcPort: 'any',
    destPort: '3306',
    protocol: 'TCP',
    action: 'DENY',
    description: 'Block direct WAN to Database — prevent external DB intrusion',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 80,
    enabled: true,
    zone: 'WAN_TO_LAN',
    srcIp: 'any',
    destIp: 'any',
    srcPort: 'any',
    destPort: '22',
    protocol: 'TCP',
    action: 'REJECT',
    description: 'Reject SSH brute-force to internal LAN — send RST',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 90,
    enabled: true,
    zone: 'WAN_TO_DMZ',
    srcIp: 'any',
    destIp: 'any',
    srcPort: 'any',
    destPort: 'any',
    protocol: 'ICMP',
    action: 'DENY',
    description: 'Block ICMP ping flood/reconnaissance from WAN',
    hitCount: 0,
    createdAt: Date.now(),
  },
  {
    id: uuidv4(),
    priority: 999,
    enabled: true,
    zone: 'ANY',
    srcIp: 'any',
    destIp: 'any',
    srcPort: 'any',
    destPort: 'any',
    protocol: 'ANY',
    action: 'DENY',
    description: 'IMPLICIT DEFAULT DENY — catch-all fallback rule',
    hitCount: 0,
    createdAt: Date.now(),
  },
];
